controller_list:
  - name: fake_StaubliArm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_BarrettHand_controller
    joints:
      - wam/bhand/finger_1/prox_joint
      - wam/bhand/finger_1/med_joint
      - wam/bhand/finger_1/dist_joint
      - wam/bhand/finger_2/med_joint
      - wam/bhand/finger_2/dist_joint
      - wam/bhand/finger_3/med_joint
      - wam/bhand/finger_3/dist_joint